apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bgokoa0tu-go 
  janus-idp.io/tekton: bgokoa0tu-go
  backstage.io/kubernetes-id: bgokoa0tu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bgokoa0tu-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml