apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: bgokoa0tu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bgokoa0tu-go 
  name: bgokoa0tu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: bgokoa0tu-go 
